### ISSUE TITLE
支持prometheus吗？

### ISSUE THREAD

**Issue by liliang8858** [alibaba/metrics#28]
支持prometheus吗？

**Comment by ralf0131** [comment]
目前不支持，计划支持中，参考[RoadMap](https://github.com/dubbo/metrics/wiki/roadmap)

**Comment by CoderPoet** [comment]
现在支持prometheus了吗？

**Comment by ralf0131** [comment]
see #43 , it is under review.

**Comment by ralf0131** [comment]
The prometheus support has been added. See https://github.com/alibaba/metrics/blob/master/metrics-prometheus/src/test/java/com/alibaba/metrics/prometheus/PrometheusExport.java for example.

**Comment by liliang8858** [comment]
比较赞
