### ISSUE TITLE
Compass getCount()方法的结果与compass.getSuccessCount()结果不一致

### ISSUE THREAD

**Issue by YaoZhichao** [alibaba/metrics#34]
每隔一分钟输出compass的数据结果
发现getCount()方法的结果与compass.getSuccessCount()结果不一致

这个现象在我们生产环境中跑一段时间就会出现，而且概率很高，
第一分钟打印
totalCount=624 successCount=619
间隔一分钟后打印
totalCount=679,successCount=679

**Comment by YaoZhichao** [comment]
代码实现：
long currentTotalCount = compass.getCount();
long currentSuccessCount = compass.getSuccessCount();

**Comment by ralf0131** [comment]
这是符合预期的，说明有些情况下没有success。
