### ISSUE TITLE
support dynamic parameter in annotation

### ISSUE THREAD

**Issue by HzjNeverStop** [alibaba/metrics#37]
Is there specific plane to support dynamic parameter in annotation?

**Comment by ralf0131** [comment]
annotation is statically processed, how can you generated it dynamically in Java?

**Comment by HzjNeverStop** [comment]
it’s useful to generate dynamic tag value in some situation, perhaps it could support another assistant annotation on fileds to mark dynamic value？

**Comment by ralf0131** [comment]
> it’s useful to generate dynamic tag value in some situation, perhaps it could support another assistant annotation on fileds to mark dynamic value？

That does not change the fact that the parameters in annotation can not be dynamic. 
If you want dynamic tag value, I think API should be used.

**Comment by HzjNeverStop** [comment]
Use reflect and aop to modifie value in annotation, or Spring EL could reach same result？i just don’t want to use to many api in middleware. of cource, I
should package a util to use the apis.

**Comment by HzjNeverStop** [comment]
Use reflect and aop to modifie tag value before execute register, or Spring EL could  reach same result？i just don’t want to use to many api in middleware. of cource, I
should package a util to use the apis.

**Comment by ralf0131** [comment]
Could you give some example you would like it to be? Please keep in mind that Spring is not a required dependency for metrics.

**Comment by HzjNeverStop** [comment]
just like argument parsing in springmvc，like this：
  @RequestMapping("/books/{bookId}")  
  public void findPet(@PathVariable String userId, @PathVariable String bookId) {      
  }

**Comment by ralf0131** [comment]
> just like argument parsing in springmvc，like this：
> @RequestMapping("/books/{bookId}")
> public void findPet(@PathVariable String userId, @PathVariable String bookId) {
> }

What if `bookId` is generated inside `findPet`?

**Comment by HzjNeverStop** [comment]
> > just like argument parsing in springmvc，like this：
> > @RequestMapping("/books/{bookId}")
> > public void findPet(@PathVariable String userId, @PathVariable String bookId) {
> > }
> 
> What if `bookId` is generated inside `findPet`?

There is a preliminary plan：
@Metric(key = "#{customBean}")
public void findPet(Object A, ....) {
}

#{customBean} means user register a springbean named "customBean"，which implement an standard interface used to generate key:

public interface KeyGenerator {
    String generateKey(Object[] args);
}

In user code:
@Component(value = "customBean")
public class xxxServiceImpl implement KeyGenerator {
    @Override
    String generateKey(Object[] args) {
        // build a key from args
    }
}

It's just a simple idea，it could be deeply optimized;
