### ISSUE TITLE
BufferPoolMetricSet采集堆外内存指标不支持JMX Client方式

### ISSUE THREAD

**Issue by RobertoHuang** [alibaba/metrics#40]
Hi 
   在使用BufferPoolMetricSet时构造函数限制传入MBeanServer

   这样是否限制了BufferPoolMetricSet只能采集Agent端的指标，而不能通过JMX Client采集指标

   是否应该将构造函数中的MBeanServer替换成MBeanServerConnection?

**Comment by ralf0131** [comment]
你的场景能详细描述一下吗，是需要采集远程的机器上的通过JMX暴露的指标吗？或者是采集本机其他进程的JMX暴露的指标？

**Comment by RobertoHuang** [comment]
嗯 需要采集远程的机器上通过JMX暴露的指标

**Comment by ralf0131** [comment]
嗯，理解了，你可以提交一个pull request，来增强这个功能。有兴趣参与吗？

**Comment by RobertoHuang** [comment]
非常乐意

支持通过JMX采集远端修改起来比较简单

有个疑问是MetricRegistry的默认实现MetricRegistryImpl，为什么不添加个删除某个指标的方法？

因为通过JMX采集远端的时候，可能因为远程应用重启或者网络原因导致需要删除之前注册的指标重新注
册，我目前使用的方法是通过反射修改了MetricRegistryImpl的metrics。好奇不提供删除监控指标的用意
是什么？

**Comment by ralf0131** [comment]
> 非常乐意
> 
> 支持通过JMX采集远端修改起来比较简单
> 
> 有个疑问是MetricRegistry的默认实现MetricRegistryImpl，为什么不添加个删除某个指标的方法？
> 
> 因为通过JMX采集远端的时候，可能因为远程应用重启或者网络原因导致需要删除之前注册的指标重新注
> 册，我目前使用的方法是通过反射修改了MetricRegistryImpl的metrics。好奇不提供删除监控指标的用意
> 是什么？

1. 注册的指标基本上都是常态化存在的，没有删除的必要
2. 对于有一些临时的指标，有自动清理机制，超过一定时间没有访问会被自动删除

如果自动删除不能满足你的诉求，可以考虑增加接口

**Comment by ralf0131** [comment]
It has been fixed by #41 , which will be available from 2.0.3 onwards.
