### ISSUE TITLE
为啥不直接依赖metrics-core、metrics-opentsdb开源项目

### ISSUE THREAD

**Issue by useraddZYB** [alibaba/metrics#45]
metrics-core和 reporter 两个module里大量代码直接粘贴复制了开源项目里代码，为啥不直接依赖进来

**Comment by ralf0131** [comment]
Hi, please check https://github.com/alibaba/metrics/wiki/introduction, which explains the reason why we forked from dropwizard metrics.

**Comment by useraddZYB** [comment]
明白
