### ISSUE TITLE
quick start  描述不完整

### ISSUE THREAD

**Issue by jkaka** [alibaba/metrics#50]
wiki中的《快速接入指南》中maven依赖2.0.0版本，可能没有打包成功，我们idea中下载不下来这个版本的jar包；后来尝试升级为2.01时能正常依赖，但仅依赖metrics-core-api模块，后面的Counter等演示代码，不能生效。还需要依赖metrics-core-impl模块，否则会报以下错误
![图片](https://user-images.githubusercontent.com/32870270/64001037-8cf5bc80-cb39-11e9-96c1-216c50390709.png)
另外，2.0.6版本依赖了metrics-core-api和metrics-core-impl模块同样会报上面这个错误。

**Comment by ralf0131** [comment]
这是符合预期的，metrics-core-api需要和metrics-core-impl结合才能实现。否则API就只有一个空实现。

**Comment by jkaka** [comment]
是的，所以建议更正下文档。文档行中只依赖了metrics-core-api

**Comment by ralf0131** [comment]
ok，明白，具体是哪个文档？

**Comment by jkaka** [comment]
wiki->快速接入指南->Jar包依赖->Maven依赖

**Comment by ralf0131** [comment]
感谢，已更新。
