### ISSUE TITLE
mac system group下不显示system.net.*信息？

### ISSUE THREAD

**Issue by GLGGAG** [alibaba/metrics#51]
在mac下,system收集不显示net.*信息，我应该如何设置？
os:10.14.6
metrics:2.0.6
![image](https://user-images.githubusercontent.com/20431373/64774742-5d0dd680-d587-11e9-8a7a-7bb0ca65e41c.png)

**Comment by ralf0131** [comment]
mac 下支持的不好，建议使用linux机器
