### ISSUE TITLE
MetricRegistry内存占用问题

### ISSUE THREAD

**Issue by davidsome** [alibaba/metrics#65]
MetricRegistry 是个map，目前代码是这么处理的，当已注册的metric数量太多时，返回一个空实现。
是否可以自动清除不活跃的metric，使得map大小合理。

**Comment by ralf0131** [comment]
com.alibaba.metrics.integrate.MetricsCleaner  这个类里面做了这个事情

**Comment by davidsome** [comment]
咨询下，看了下代码，为啥counter的lastUpdateTime 是 返回System.currentTimeMillis()，这个说明实际没起作用吗？
